create table familys(
    id number GENERATED BY DEFAULT AS IDENTITY,
    name varchar(16) not null,
    address varchar(150 char) not null,
    patriarch number,
    primary key(id)
    );
    
create table persons(
    id number GENERATED BY DEFAULT AS IDENTITY,
    name varchar(16) not null,
    family_id number not null,
    birth date not null,
    sex number(1),
    marriage number,
    parent number(1) default 0 not null,
    death number(1) default 0 not null,
    primary key(id),
    CONSTRAINT fk_person_family FOREIGN KEY (family_id)
        REFERENCES familys(id)
    );
    

create table history(
    id number GENERATED BY DEFAULT AS IDENTITY,
    person_id number not null,
    family_id number not null,
    primary key(id),
    CONSTRAINT fk_history_family FOREIGN KEY (family_id)
        REFERENCES familys(id),
     CONSTRAINT fk_history_person FOREIGN KEY (person_id)
        REFERENCES persons(id)
   );
